# fly.toml app configuration file generated for senate-jolt on 2026-10-08T00:42:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'senate-jolt'
primary_region = 'iad'

[build]

[env]
  SENATE_WIRE_DATABASE_URL = 'sqlite:////data/senate_wire.db'

[[mounts]]
  source = 'sj_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
